---
- name: Verify download dir exists
  tags: magento
  sudo: no
  local_action: file
    path={{ magento_download_tmp_dir }}
    state=directory
    owner=0
    group=0
    mode={{ magento_download_tmp_dir_mode }}

- name: Verify download remote dir exists
  tags: magento
  file:
    path={{ magento_install_tmp_dir }}
    state=directory

- name: Download Magento in given Version
  tags: magento
  sudo: no
  when: magento_download == 'yes'
  local_action: get_url
    url={{ magento_download_host }}/{{ magento_download_package }}
    dest={{ magento_download_tmp_dir }}/{{ magento_download_package }}
    mode=0644

- name: Copy installation archive
  tags: magento
  when: magento_copy != 'yes'
  copy:
    src="{{ magento_download_tmp_dir }}/{{ magento_download_package }}"
    dest="{{ magento_install_tmp_dir }}/{{ magento_download_package }}"
    owner=0
    group=0
    mode=0644

- name: Extract Magento
  tags: magento
  sudo: yes
  sudo_user: "{{ magento_webuser }}"
  when: magento_copy != 'yes' and '{{ magento_webuser }}' != '{{ ansible_user_id }}'
  unarchive:
    src="{{ magento_install_tmp_dir }}/{{ magento_download_package }}"
    dest="{{ magento_install_tmp_dir }}/"
    copy=no

- name: Extract Magento
  tags: magento
  when: magento_copy != 'yes' and '{{ magento_webuser }}' == '{{ ansible_user_id }}'
  unarchive:
    src="{{ magento_install_tmp_dir }}/{{ magento_download_package }}"
    dest="{{ magento_install_tmp_dir }}/"
    copy=no

- name: Copy magento from local
  tags: magento
  when: magento_copy == "yes"
  copy:
    src={{ magento_copy_local_dir }}
    dest={{ magento_install_tmp_dir }}

- name: Change owner and group
  tags: magento
  file:
    path={{ magento_install_tmp_dir }}/{{ magento_install_tmp_dir_sub |default('magento') }}
    owner={{ magento_webuser }}
    group={{ magento_webgroup }}
    recurse=yes
    state=directory

- name: Move to Magento-Root-Dir
  tags: magento
  command:
    "rsync -av
    -p --chmod=Du=rwx --chmod=Dg=rx --chmod=Do= --chmod=Fu=rw --chmod=Fg=r --chmod=Fo=
    {{ magento_install_tmp_dir }}/{{ magento_install_tmp_dir_sub |default('magento') }}/
    {{ magento_root }}/"

    #rsync_opts="--chmod=D2750,--chmod=F640"
    #
- name: Create Magento-Install script
  tags: magento
  template:
    src=magento-install.j2
    dest={{ magento_install_tmp_dir }}/magento-install.sh

- name: Remove app/etc/local.xml if exists
  tags: magento
  file:
    state=absent
    path="{{ magento_root }}/app/etc/local.xml"

- name: Install Magento local.xml.template
  tags: magento
  template:
    src={{ magento_local_template|default('local.xml.template.j2') }}
    dest={{ magento_root }}/app/etc/local.xml.template

- name: Notify install
  tags: magento
  notify: run magento install
  command: /bin/true
