---

- name: Register existing installation
  tags: magento
  register: magento_register_localxml
  stat:
    path={{ magento_root }}/app/etc/local.xml

- name: Set magento_install variable
  tags: magento
  when: not magento_register_localxml.stat.exists
  set_fact:
    magento_install=true

- include: "install.yml"
  tag: magento
  when: magento_install

- name: Notify permissions verify
  tags: magento
  notify:
    - Verify user
    - Verify permissions
  command: /bin/true

- include: "modman.yml"
  tags:
    - magento
    - modman
  when: magento_modman == "yes"
