---
- name: Include Magento Tasks
  tags: magento
  when: magento_manage_magento
  include: magento.yml

- name: Include Modman Tasks
  tags:
    - magento
    - modman
  when: magento_modman
  include: modman.yml
