---

- name: Install modman
  tags: 
    - magento 
    - modman
  get_url:
    url=https://raw.github.com/colinmollenhour/modman/master/modman
    dest={{ magento_modman_bin_dir }}/modman
    mode="0755"
    owner={{ magento_webuser}}
    group={{ magento_webgroup }}

- name: Check modman dir exists
  tags: 
    - magento 
    - modman
  register: check_modman
  stat: path={{ magento_root }}/.modman

- name: modman Init magento
  tags: 
    - magento 
    - modman
  when: check_modman.stat.exists == false
  command: chdir={{ magento_root }} {{ magento_modman_bin_dir }}/modman init

- name: Install git 
  tags: 
    - magento 
    - modman
  action: "{{ ansible_pkg_mgr }} state=installed name=git"

- name: Check extensions already checked out
  tags: 
    - magento 
    - modman
  register: magento_modman_extensions_dirs
  with_items: magento_modman_extensions_git
  stat: path={{item.dest}}

- name: Update git remote
  tags: 
    - magento 
    - modman
  when: item[0].stat.isdir is defined and item[0].stat.isdir == true
  with_together: 
    - magento_modman_extensions_dirs.results
    - magento_modman_extensions_git
  shell: >
    chdir={{item[1].dest}}
    free_form=yes
    git remote set-url {{item[1].remote|default('origin')}} {{ item[1].repo }}

- name: Install Extensions from git 
  tags: 
    - magento 
    - modman
  with_items: magento_modman_extensions_git
  git:
    repo="{{item.repo}}"
    dest="{{item.dest}}"
    version="{{item.version|default('HEAD')}}"
    remote="{{item.remote|default('origin')}}"
    key_file="{{item.key_file|default(None)}}"
    ssh_opts="{{item.ssh_opts|default(None)}}"
    accept_hostkey="{{item.accept_hostkey|default('no')}}"
    bare="{{item.bare|default('no')}}"
    depth="{{item.depth|default(0)}}"
    executable="{{item.executable|default('')}}"
    reference="{{item.reference|default('')}}"
    force="{{item.force |default('yes')}}"
    update="{{item.gitupdate|default('yes')}}"

- name: Add extensions to registerd variable 
  with_items: 
    - "{{ magento_modman_extensions_git }}"
    - "{{ magento_modman_extensions_other }} "
  register: magento_modman_extensions
  notify: 
    - rm links
    - modman link all
  shell: echo "{{item.dest}}"

