---

- name: rm links 
  notify:
    - modman clean
  shell:  rm -f {{ magento_root }}/.modman/*

- name: modman clean
  shell:
    chdir={{ magento_root }} 
    free_form=yes
    {{ magento_modman_bin_dir }}/modman clean

- name: modman link all
  ignore_errors: yes
  with_items: magento_modman_extensions.results
  notify:
    - modman deploy-all
    - modman repair
  shell: 
    chdir={{ magento_root }}
    free_form=yes 
    {{ magento_modman_bin_dir }}/modman link {{item.stdout}}

- name: modman deploy-all
  shell:
    chdir={{ magento_root }}
    free_form=yes
    "{{ magento_modman_bin_dir }}/modman" deploy-all --force

- name: modman repair
  shell:
    chdir={{ magento_root }}
    free_form=yes 
    {{ magento_modman_bin_dir }}/modman repair

- name: verify permissions
  with_items: magento_permissions_list
  shell: >
    chdir={{ magento_root }} 
    free_form=yes
    find . -type {{ item.type }} -exec 
    install -{{ item.type }}  
    -m {{ item.mode }} 
    -o {{ item.owner|default( magento_webuser )  }} 
    -g {{ item.group|default( magento_webgroup )  }} {} \; 

- name: run magento install
  shell: 
    free_form=yes
    sh {{ magento_install_tmp_dir }}/magento-install.sh
