---

- name: handle modman extensions links
  notify: modman clean
  ignore_errors: yes
  shell:
    sh {{ magento_install_tmp_dir }}/handle_extensions.sh

- name: modman clean
  shell:
    chdir={{ magento_root }}
    free_form=yes
    {{ magento_modman_bin_dir }}/modman clean

- name: modman deploy-all
  shell:
    chdir={{ magento_root }}
    free_form=yes
    "{{ magento_modman_bin_dir }}/modman" deploy-all --force

- name: modman repair
  shell:
    chdir={{ magento_root }}
    free_form=yes
    {{ magento_modman_bin_dir }}/modman repair

- name: run magento install
  shell:
    free_form=yes
    sh {{ magento_install_tmp_dir }}/magento-install.sh

- name: Verify user
  file:
    path={{ magento_install_tmp_dir }}/magento
    owner={{ magento_webuser }}
    group={{ magento_webgroup }}
    recurse=yes
    state=directory

- name: Verify permissions
  with_items: magento_permissions_list
  shell: >
    chdir={{ item.dir}}
    free_form=yes
    find . -type {{ item.type }} -exec
    chmod {{ item.mode }} {} \; ;
